### ISSUE TITLE
Pluggable authorization middleware

### ISSUE THREAD

**Issue by benwiz** [life-research/blaze#50]
## Problem 

Blaze does not support [FHIR's authorization for resource access control](https://www.hl7.org/fhir/security.html#binding). 

Every deployment of Blaze may have unique authorization providers and access control protocols.

## Proposed Solution

Blaze should be deployed with a free-floating jar added to the classpath during launch. The authorization jar will provide a custom middleware for handling authorization. Initialization will be managed by Integrant.

### Details

- The authorization jar must be added to the classpath during launch. For example, `java -cp blaze.jar:my-authorization.jar blaze.core`.
- The fully qualified namespace must be provided with an environment variable named `AUTHORIZATION_NS`.
- Prior to starting Integrant... If `AUTHORIZATION_NS` is non-nil and non-empty, try `requiring-resolve` on the provided path. If error, exit with informative error message without starting Integrant.
  - Can consider checking for the existence of the `OPENID_PROVIDER_URL` env var because the `identity` key on request will likely be required.
- The provided namespace must extend `ig/init-key` (and `ig/halt-key!` where appropriate)
  - `ig/init-key` should return a ring middleware 
  - Can consider checking for the existence of the `init-key :authorization` method using `(keys (methods ig/init-key))` after using `requiring-resolve` on `AUTHORIZATION_NS`. This is another pre-Integrant exit point.

#### Other notes
- The authorization service can use the provided database connection but could choose to ignore it 
- We could consider that the provided namespace should also expose a var whose value is the key that will be used for Integrant, for example `(def key :authorization)`. In the beginning, I intend the key to be hardcoded to `:authorization`.

### Pros

- Custom authorization implementation for every Blaze deployment
- Blaze needs to know nothing about configuration for the authorization service
- Fail fast if authorization namespace cannot be found
- Leverage existing Integrant + middleware architecture

### Cons

- Configuration of the authorization service (for example, database) will take more effort than a solution integrated directly into Blaze

**Comment by alexanderkiel** [comment]
## Additional things to consider

We have to find a way how the plugin can define it's dependencies and config. I mean a combination of what can be found under `default-config` in `blaze.system` and the specs needed to coerce the environment variables.

There is a potential to run into Classpath problems. The additional Jar could bring a different version of a lib say buddy. With that we could have different versions of the same lib in our single Classpath leading to really nasty problems. In my opinion a real plugin architecture would need to use something like OSGi. But I never heard of someone from the Clojure community to use it. Do you have experience with plugin architectures in Clojure?

Aside from that two points using Integrant with the multimethods an Ring middleware is a super elegant way to introduce any cross cutting aspect into Blaze. If we get that working, I would even use that plugin mechanism for authentication.

## Things to consider at deployment time

There could be a Docker image containing various plugin Jars which all work together. A startup script could load the plugins based on env vars. Such a "official" Docker image would somehow mitigate the Classpath problem because we could ensure compatibility between plugins.

## Complete other Ideas

Introducing a real plugin system to Blaze would be a more monolithic approach rather than a micro service one. Using OSGi would be a good indicator leaving micro service territory to me. I don't say that the mirco service architecture is a good solution for everything. But we should also think about outsourcing authentication/authorization out of Blaze core. Originally I had the idea to use something like Envoy for external authentication/authorization for Blaze but haven't started to evaluate it.

**Comment by dspiteself** [comment]
In my experience OSGI ends up being a black hole of issues. I think for almost any one this would be an advanced option and a deployment time not run time concern.  I propose documenting adding blaze to the [provided profile](https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md#framework-uberjars) for the authorization "plugin". We use this to much success for other projects like Apache Storm.

**Comment by dspiteself** [comment]
Using Envoy or other reverse proxies will cause a lot of duplicated work. I an not saying that is horrible, but often one has to load a resource to determine if a user has access to if for anything more sophisticated that RBAC.

**Comment by alexanderkiel** [comment]
>In my experience OSGI ends up being a black hole of issues.

I agree with you here.

>I propose documenting adding blaze to the [provided profile](https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md#framework-uberjars) for the authorization "plugin". We use this to much success for other projects like Apache Storm.

That is a good idea. It's not a perfect solution because we'll still face versioning issues. But better than nothing.

**Comment by alexanderkiel** [comment]
> Using Envoy or other reverse proxies will cause a lot of duplicated work. I an not saying that is horrible, but often one has to load a resource to determine if a user has access to if for anything more sophisticated that RBAC.

Can you describe that kind of authorization you will need? I currently read everything, I can find about Authorization in the FHIR Context. I will not rule out a plugin system. But perhaps we could also implement some authorization schema which is sufficient for your needs and also for many others. Although I know that Authorization is a very complex field with very special needs.

**Comment by alexanderkiel** [comment]
If you read through the [General Considerations](https://www.hl7.org/fhir/security.html#general) I would prefer the first example of an external security system which itself mimics a FHIR API and uses Blaze only as storage. It may be not possible to implement such a system with Envoy alone but I could imagine a system implemented in Clojure which can wrap any FHIR server adding just authentication/authorization and maybe audit logs. Such a system would be completely independent of Blaze and not only useful together with Blaze.

**Comment by alexanderkiel** [comment]
This might be also of interest: http://hl7.org/fhir/smart-app-launch/index.html

**Comment by alexanderkiel** [comment]
In general, I'm not against a plugin system. In particular, I would like to implement FHIR operations as plugins. Currently I implemented $evaluate-measure for CQL support already. I really would like to see it as plugin rather than in the core.

I found that [Metabase](https://github.com/metabase/metabase) has a plugin system which currently seems only to be used for drivers but they also plan to use it for other things. 

* https://github.com/metabase/metabase/wiki/Writing-a-Driver:-Packaging-a-Driver-&-Metabase-Plugin-Basics
* https://github.com/metabase/metabase/pull/9087

They have quite some [classloading](https://github.com/metabase/metabase/blob/master/src/metabase/plugins/classloader.clj) stuff going on. This allows them to just load the plugins from a directory, so you don't need to specify the jars with `-cp`. I currently don't see whether the use of a separate Classloader will mitigate the problem of having different versions of the same jar. I'll ask that question on there gitter later today.

**Comment by dspiteself** [comment]
One thing to remember is that class loader isolation does not isolate clojure. All clojure code will be evaluated in the class loader that loaded Clojure. This would not enable different versions of clojure dependencies only the java dependencies they depend on.

**Comment by dspiteself** [comment]
Also Alex was talking about including the [add-lib](https://github.com/clojure/tools.deps.alpha/blob/add-lib/src/main/clojure/clojure/tools/deps/alpha/repl.clj) from tools deps to core. This would allow you to delay the loading to runtime. I know classpath isolation is possible, I don't think class path isolation is worth the complexity. Another clean option would be for plugin maintainers to collaborate to keep a deps edn file that satisfied all the plugins with each one as an alias. It could have a test sweet for all the plugins and run ci on changes. The whole project would be a deps edn file and documentation. 
`clj -R:plugin1:plugin2 -m start.blaze`

**Comment by alexanderkiel** [comment]
I'm happy that you mention deps.edn. Over the weekend, I started to convert Blaze from Leiningen to deps.edn. You can see the progress in the [modular](https://github.com/life-research/blaze/tree/modular) branch. I have evaluated OSGi further and you are right, it doesn't work well with Clojure. I plan to cut Blaze into modules but leave them in the same repo just in different dirs. I plan to have vertical features like $evaluate-measure and horizontal things like auth in separate modules which can be enabled/disabled at deploy time like feature toggles. Currently the build artifact is an uberjar but using `clj` to run Blaze could be also an option. In my project I need a deploy option under Windows without Docker. So an uberjar is ideal there.

Also if Blaze is fully modular with a very thin core module at the root, it would be possible for others to pick a set of "official" modules through git references, add their own ones and put together the classpath with their own core module. 

What do you think about this approach?

**Comment by dspiteself** [comment]
I really like that approach. The question left on the table is configuration and initialization/discovery. How do we inject middleware etc? I think it is sufficient for now that the core module defines them for now, but in the future it would be cool to have hooks that could modify a data structure representing the server and endpoints. On the other hand it will be hard to get much composeability other than registering new operations or overriding a resources functionality.  An example of a extensiblity goal I would have would be enabling two encoding for date one binary and one tuple based.

**Comment by dspiteself** [comment]
Another option I discussed before would be to use a [vase](https://github.com/cognitect-labs/vase) like approach where you would read the fhir profiles build the data structure for the endpoints that composes functions from the modules. We would provide one for the base modules and people like use would just customize our own to integrate our modules. Most entirely general frameworks for module composition I haven't seen work well in java land. Interceptors and middleware work pretty well and It is likely we could make some for special case definition like matching fhir schema from datomic to json and from parameters to a datomic query fragment.

**Comment by alexanderkiel** [comment]
One integration point I see is a module providing an Integrant config map together with a `defmethod`, as you already suggested. I already tested this:

```clojure
(ns blaze.breeze.authorization.core
  (:require
    [integrant.core :as ig]
    [taoensso.timbre :as log]))


(def config
  {:module.breeze.authorization/middleware
   {:database/conn (ig/ref :core/database-conn)}})


(defmethod ig/init-key :module.breeze.authorization/middleware
  [_ _]
  (log/info "Init Breeze Authorization"))
```

In `blaze.system`, we would require the namespace `blaze.breeze.authorization.core` dynamically and merge it's config into the core config:

```clojure
(ns blaze.system
  (:require
    [clojure.spec.alpha :as s]
    [clojure.string :as str]
    [datomic.api :as d]
    [integrant.core :as ig]
    [taoensso.timbre :as log]))


(s/def :module.breeze.authorization/enable
  boolean?)


(s/def :system/config
  (s/keys
    :opt
    [:module.breeze.authorization/enable]))


(def ^:private default-config
  {:core/database-conn
   {:database/uri "datomic:mem://dev"}})


(defn- merge-module-config [config sym]
  (merge-with merge config (var-get (requiring-resolve sym))))


(s/fdef init!
  :args (s/cat :config :system/config))

(defn init!
  [{:log/keys [level] :or {level "info"} :as config}]
  (log/info "Set log level to:" (str/lower-case level))
  (log/merge-config! {:level (keyword (str/lower-case level))})
  (let [config
        (cond-> config
          (:module.breeze.authorization/enable config)
          (-> (dissoc :module.breeze.authorization/enable)
              (merge-module-config `blaze.breeze.authorization.core/config)))]
    (ig/init (merge-with merge default-config config))))


(defmethod ig/init-key :core/database-conn
  [_ {:database/keys [uri] :keys [structure-definitions]}]
  (if (d/create-database uri)
    (do
      (log/info "Created database at:" uri)
      #_(upsert-schema uri structure-definitions))
    (log/info "Use existing database at:" uri))

  (log/info "Connect with database:" uri)
  (d/connect uri))
```

I think, we could do that `:module.breeze.authorization/enable` thing without knowing the module in advance. We just have to find a way to enumerate all `enable` flags.

>An example of a extensiblity goal I would have would be enabling two encoding for date one binary and one tuple based.

Thats a different thing for sure.

I currently build modules from the current blaze source. If we have that, the picture should look clearer. Please be aware that I might not have much time left this week as I'm actually on holiday.

**Comment by dspiteself** [comment]
If we did do the vase approach we would generate a route for each resource with the type statically in the route. That would enable attaching custom authorization interceptors on a per type and method basis. I will make a mockup of this at some point. Again no need to respond now. Enjoy your holiday!

**Comment by alexanderkiel** [comment]
@dspiteself I have already split everything into modules. You can see the work in progress [here](https://github.com/life-research/blaze/tree/modular). It's still work in progress.

I also took inspiration from vase. My goal is to be able to run a modular Blaze with only a [blaze.edn](https://github.com/life-research/blaze/blob/modular/blaze.edn) and an appropriate `deps.edn`. `blaze.edn` essentially is an Integrant config map. 

Each individual module registers itself on an Integrant key which is the same as the namespace it uses. The cool thing is, that you can now use Integrants [load-namespaces](https://github.com/weavejester/integrant#loading-namespaces) function to load all namespaces from all keys. That will work if `deps.edn` provides the right class path. The important thing is, that you don't need to write code to include a new module. 

If you look at the `:blaze/rest-api` key, it contains a `:config` which specifies which interactions and operations should be included in the REST API. Here you can refer to implementations of special operations though Integrant references. The same can be done for middleware. In the `blaze.rest-api` namespace, I build the routes and (not done yet) the capability statement from this config. So you can specify exactly that the REST API should include. You can also specify special middleware on special resource types (not done yet). I called the config key `resource-pattern` instead of `resource` because I want to be able to use regex, collections and `:default` in `:type`. So you don't have to specify all resources you want to include. 

At the end, we should think about hiding Integrant. But for now I would go with it. Integrant really brings all we need to dynamically load namespaces and wire all modules together. Integrant even has a notion of key hierarchies. You can see that at the `:blaze/terminology-service` key. Here I instantiate the concrete `:blaze.terminology-service/extern` but can refer to it under `:blaze/terminology-service`. With this we could realize different implementations of the DateTime schema stuff.

What do you think about my approach?

**Comment by dspiteself** [comment]
I like it! I will tell you more as I continue to look at it. `#:blaze.rest-api.resource-pattern` could take middle-ware right?

**Comment by alexanderkiel** [comment]
Yes it could hold middleware.

**Comment by dspiteself** [comment]
Yea I think this will work great for all our needs. Tell us if you want to split out any of these tasks and give them to us. In the absence of direction from you we will focus on generating blaze.edn files for our 2 extensions(authorization and additional search params).  We will do the search param work in our fork of this repo if it does not match your desires we can split the module out into another repo.

**Comment by dspiteself** [comment]
```#:blaze.rest-api.resource-pattern
            {:type "Patient"
             :interactions
             {:search-type
              {:handler #ig/ref :blaze.interaction/search-type}
              :read
              {:handler #ig/ref :blaze.interaction/read}}}``` 
will need to be a little more structured to support generating a capability statement. For instance you will need to be able to see what search parameters are supported.

**Comment by alexanderkiel** [comment]
> Yea I think this will work great for all our needs. Tell us if you want to split out any of these tasks and give them to us. In the absence of direction from you we will focus on generating blaze.edn files for our 2 extensions(authorization and additional search params). 

Yes that would be good.

>We will do the search param work in our fork of this repo if it does not match your desires we can split the module out into another repo.

Please keep it in the fork, because I like to have the search params as "official" Blaze module. For the authorization module, I think it depends whether it is very specific to your use-case or whether it is more generic.

**Comment by benwiz** [comment]
Opened a pull request, so closing this issue
https://github.com/life-research/blaze/pull/96
